### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by ghost** [FeeiCN/GSIL#2]
Traceback (most recent call last):
  File "gsil.py", line 28, in <module>
    sys.exit(gsil())
  File "/Users/xxxxxx/GithubSIL/gsil/__init__.py", line 100, in gsil
    start(sys.argv[1])
  File "/Users/alchu4n/GithubSIL/gsil/__init__.py", line 65, in start
    rules = get_rules(rule_types)
  File "/Users/xxxxxx/GithubSIL/gsil/config.py", line 160, in get_rules
    for types, rule_list in rules_dict.items():
NameError: name 'rules_dict' is not defined

**Comment by FeeiCN** [comment]
因为你没有配置rules.gsil
