### ISSUE TITLE
运行错误 

### ISSUE THREAD

**Issue by graySava** [FeeiCN/GSIL#21]
```
root@kali:~/gsil# python3 gsil.py  test 
Traceback (most recent call last):
  File "gsil.py", line 20, in <module>
    from gsil import gsil
  File "/root/gsil/gsil/__init__.py", line 19, in <module>
    from .engine import Engine
  File "/root/gsil/gsil/engine.py", line 18, in <module>
    from github import Github, GithubException
ImportError: No module named 'github'
```

另外github的token生成了之后在脚本的哪里写入....小白表示很懵逼

**Comment by FeeiCN** [comment]
没有安装依赖
`pip install -r requirements.txt`

将`gsil/config.gsil.example`重命名为`gsil/config.gsil`，写在其中的`tokens`行
