### ISSUE TITLE
Exception: json decoder

### ISSUE THREAD

**Issue by FeeiCN** [FeeiCN/GSIL#23]
少数情况下会有以下异常
```python
/var/app/gsil/gsil.py meili 
Traceback (most recent call last): 
File "/var/app/gsil/gsil.py", line 28, in sys.exit(gsil()) 
File "/var/app/gsil/gsil/__init__.py", line 102, in gsil generate_report(running_data) 
File "/var/app/gsil/gsil/__init__.py", line 83, in generate_report run_data = daily_run_data() 
File "/var/app/gsil/gsil/config.py", line 293, in daily_run_data c = json.loads(c) 
File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads return _default_decoder.decode(s) 
File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
File "/usr/local/lib/python3.6/json/decoder.py", line 355, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 122847 (char 122846)
```

**Comment by FeeiCN** [comment]
https://github.com/FeeiCN/GSIL/commit/8b73fe84a357765cf2896a91e8b7b76bc668447c
