### ISSUE TITLE
邮箱错误

### ISSUE THREAD

**Issue by glwm2345** [FeeiCN/GSIL#34]
使用outlook邮件服务器会报错误，如下
2018-09-28 13:17:11,480 [GSIL] [CRITICAL] Send mail failed
Traceback (most recent call last):
  File "/root/tools/GSIL/gsil/notification.py", line 71, in notification
    s.sendmail(mail, self.to.split(',')+self.cc.split(','), msg.as_string())
  File "/usr/local/python3/lib/python3.6/smtplib.py", line 887, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'5.7.1 Client does not have permissions to send as this sender')

**Comment by whoadmin** [comment]
同样的错误

**Comment by FeeiCN** [comment]
是否在邮箱里启用了客户端功能，或者换个邮件吧
