### ISSUE TITLE
出现这个错误不知如何解决

### ISSUE THREAD

**Issue by wangtufly** [FeeiCN/GSIL#36]
Traceback (most recent call last):
  File "/usr/gsil/gsil/__init__.py", line 37, in search
    return Engine(token=token).search(rule)
  File "/usr/gsil/gsil/engine.py", line 217, in search
    Process(self.result, self.rule_object).process()
  File "/usr/gsil/gsil/process.py", line 36, in process
    ret_mail = self._send_mail(maybe_mistake)
  File "/usr/gsil/gsil/process.py", line 69, in _send_mail
    return Notification(subject, to, cc).notification(html)
  File "/usr/gsil/gsil/notification.py", line 66, in notification
    s = smtplib.SMTP(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by FeeiCN** [comment]
邮件地址不可达，看看是不是你网络问题
