### ISSUE TITLE
 Error: No section: 'github'

### ISSUE THREAD

**Issue by laolong123** [FeeiCN/GSIL#39]
github tokens
Traceback (most recent call last):
  File "/root/gsil/gsil/config.py", line 42, in get
    value = config.get(level1, level2)
  File "/usr/local/sbin/python-3.7.0a1/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/local/sbin/python-3.7.0a1/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'github'
GSIL/config.gsil file configure failed.
Error: No section: 'github'
2018-11-02 08:07:09,837 [GSIL] [CRITICAL] github -> tokens sections error Traceback (most recent call last):
  File "/root/gsil/gsil/config.py", line 53, in <module>
    if ',' in tokens:
TypeError: argument of type 'NoneType' is not iterable

**Comment by FeeiCN** [comment]
正确的配置GSIL/config.gsil文件

**Comment by shenjian216** [comment]
错的一模一样，到底是哪这个文件里的哪一个东西没配置对呢
