### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by LostNF** [FeeiCN/GSIL#40]
python3 gsil.py test
2018-11-18 22:21:34,056 [GSIL] [INFO] start monitor github information leakage: test
2018-11-18 22:21:34,056 [GSIL] [INFO] rules length: 1
2018-11-18 22:21:34,069 [GSIL] [INFO] >>>>>>>>>>>>> mogujie.com > "mogujie.org" >>>>>>
Traceback (most recent call last):
  File "/root/gsil/gsil/__init__.py", line 37, in search
    return Engine(token=token).search(rule)
  File "/root/gsil/gsil/engine.py", line 161, in search
    rate_limiting = self.g.rate_limiting
  File "/usr/local/lib/python3.7/site-packages/github/MainClass.py", line 123, in rate_limiting
    self.get_rate_limit()
  File "/usr/local/lib/python3.7/site-packages/github/MainClass.py", line 145, in get_rate_limit
    '/rate_limit'
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 277, in __requestRaw
    requestHeaders
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by LostNF** [comment]
用 python3 gsil.py --verify-tokens 测试了下发现可以发送邮件到邮箱，内容就是报错的信息，为什么github会拒接链接。

**Comment by FeeiCN** [comment]
看看是否可以连通github

**Comment by LostNF** [comment]
> 看看是否可以连通github

可能是因为环境的问题，换了新的服务器可以正常运行，顺便想向您请教下，对于企业来说有必要收集的特征信息有哪些。

**Comment by GSIL-Monitor** [comment]
@LostNF https://feei.cn/gsil 这里面有讲到

**Comment by FeeiCN** [comment]
@LostNF https://feei.cn/gsil 这里面有讲到

**Comment by LostNF** [comment]
> @LostNF https://feei.cn/gsil 这里面有讲到

现在遇到一个问题，扫描到的内容不匹配skip的特别多，同时github api有限制每次只能搜索到1000条内容，可能导致扫描不全的问题，您这边有好的解决方案吗。

**Comment by FeeiCN** [comment]
@LostNF 多加几个token

**Comment by LostNF** [comment]
> @LostNF 多加几个token

为什么扫描会出现大量的   Did not match the code, skip!  呢

**Comment by FeeiCN** [comment]
@LostNF 被内置规则判断为了没有有效的可用信息，就会跳过了。

**Comment by cqf539** [comment]
总是被GITHUB BAN掉，在一些位置增加了sleep(1)的动作（只能再延长sleep时间来缓解），还是会被拒绝，不知道是否有遇到过。针对多加几个token，看代码是创建多进程，每个进程处理一个规则，好像也不能解决被官方拒绝的情况。

**Comment by w2n1ck** [comment]
> 总是被GITHUB BAN掉，在一些位置增加了sleep(1)的动作（只能再延长sleep时间来缓解），还是会被拒绝，不知道是否有遇到过。针对多加几个token，看代码是创建多进程，每个进程处理一个规则，好像也不能解决被官方拒绝的情况。

一样的问题
