### ISSUE TITLE
gsli 运行问题

### ISSUE THREAD

**Issue by ximiluliyi** [FeeiCN/GSIL#41]
github的token已经使用了，   但是在使用 python gsil.py test 的时候报错：

('github', 'tokens')
Traceback (most recent call last):
  File "/root/gsil/gsil/config.py", line 42, in get
    value = config.get(level1, level2)
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 792, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 1162, in _unify_values
    raise NoSectionError(section)
NoSectionError: No section: 'github'
GSIL/config.gsil file configure failed.
Error: No section: 'github'
2018-11-22 15:36:42,686 [GSIL] [CRITICAL] github -> tokens sections error Traceback (most recent call last):
  File "/root/gsil/gsil/config.py", line 53, in <module>
    if ',' in tokens:
TypeError: argument of type 'NoneType' is not iterable

**Comment by FeeiCN** [comment]
配置文件有问题，查看根目录下config.gsil文件
