### ISSUE TITLE
请教运行的问题

### ISSUE THREAD

**Issue by ximiluliyi** [FeeiCN/GSIL#42]
您好。  我按照你的操作执行到 检测的时候，运行：python gsil.py test 后，  执行完了后就报错说我邮件配置的问题，  我使用自己的QQ邮箱配置的，  还是不行， 然后我直接没有配置了，还是报错。 在配置了qq邮箱的时候报错如下：
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: '1312**87@qq.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farmsec/gsil/gsil/config.py", line 42, in get
    value = config.get(level1, level2)
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: '1312**87@qq.com'
GSIL/config.gsil file configure failed.
Error: No section: '13128**87@qq.com'
Traceback (most recent call last):
  File "/home/farmsec/gsil/gsil/__init__.py", line 37, in search
    return Engine(token=token).search(rule)
  File "/home/farmsec/gsil/gsil/engine.py", line 217, in search
    Process(self.result, self.rule_object).process()
  File "/home/farmsec/gsil/gsil/process.py", line 36, in process
    ret_mail = self._send_mail(maybe_mistake)
  File "/home/farmsec/gsil/gsil/process.py", line 69, in _send_mail
    return Notification(subject, to, cc).notification(html)
  File "/home/farmsec/gsil/gsil/notification.py", line 70, in notification
    s.login(mail, get('1312**87@qq.com', 'LIyi..00'))
  File "/usr/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.6/smtplib.py", line 638, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'

然后我直接没有配置了， 保持您的默认的那样还是报错，  如下：
Traceback (most recent call last):
  File "/home/farmsec/gsil/gsil/notification.py", line 70, in notification
    s.login(mail, get('mail', 'password'))
  File "/usr/lib/python3.6/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.6/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
请问下是什么原因呢？  谢谢哦    如果方便的话能留下您的QQ吗？

**Comment by FeeiCN** [comment]
配置有问题，贴下你的config.gsil配置文件看下

**Comment by ximiluliyi** [comment]
我的config.gsil配置如下：
[mail]
host : smtp.exmail.qq.com
port : 25
mails :131299××87@qq.com
from : GSIL
password : ×××××
to : feei@feei.cn
cc : feei@feei.cn

[github]
clone: false
tokens : e9b055ad1ad07f41d5bcb32db58a80×××9306ad

**Comment by FeeiCN** [comment]
看这行应该是你邮箱这行配置的有问题，尝试mails的冒号后面加个空格试试？
```python
GSIL/config.gsil file configure failed.
Error: No section: '1312887@qq.com'
```

或者将整个config删掉，然后再从模板copy一份试试
```bash
➜  gsil git:(master) ✗ cat config.gsil
[mail]
host : smtp.exmail.qq.com
port : 25
mails : reply@feei.cn
from : GSIL
password : xxx
to : feei@feei.cn
cc : feei@feei.cn

[github]
clone: false
tokens : 6xxx
```

**Comment by ximiluliyi** [comment]
我重新按照您的提示做了，  又又又又报错了：

mail cc
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farmsec/gsil/gsil/config.py", line 42, in get
    value = config.get(level1, level2)
  File "/usr/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'cc' in section: 'mail'
GSIL/config.gsil file configure failed.
Error: No option 'cc' in section: 'mail'
mail cc
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'cc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farmsec/gsil/gsil/config.py", line 42, in get
    value = config.get(level1, level2)
  File "/usr/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'cc' in section: 'mail'
GSIL/config.gsil file configure failed.
Error: No option 'cc' in section: 'mail'
2018-11-26 09:51:16,223 [GSIL] [CRITICAL] Send mail failed
Traceback (most recent call last):
  File "/home/farmsec/gsil/gsil/notification.py", line 70, in notification
    s.login(mail, get('mail', 'password'))
  File "/usr/lib/python3.6/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.6/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
2018-11-26 09:51:17,165 [GSIL] [CRITICAL] GitHub [get_page] exception(code: 403 msg: {'documentation_url': 'https://developer.github.com/v3/#abuse-rate-limits', 'message': 'You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.'} be8cbc7a52f2c3ad8052dc41×××4b1e64a4b2b0f

**Comment by FeeiCN** [comment]
config.gsil中的cc是不是没填
```
raise KeyError(key)
KeyError: 'cc'
```

**Comment by notwhy** [comment]
遇到相同问题，运用以下方法解决。需要个人qq开启smtp
https://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=371
在config password填写你开启后的授权码
地址改为smtp.qq.com
端口改为465即可

**Comment by lipangbo** [comment]
github tokens
Traceback (most recent call last):
File "H:\python\lib\configparser.py", line 1138, in _unify_values
sectiondict = self._sections[section]
KeyError: 'github'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "H:\GSIL\gsil\config.py", line 42, in get
value = config.get(level1, level2)
File "H:\python\lib\configparser.py", line 781, in get
d = self._unify_values(section, vars)
File "H:\python\lib\configparser.py", line 1141, in _unify_values
raise NoSectionError(section)
configparser.NoSectionError: No section: 'github'
GSIL/config.gsil file configure failed.
Error: No section: 'github'
2020-08-08 18:55:23,084 [GSIL] [CRITICAL] github -> tokens sections error Traceb
ack (most recent call last):
File "H:\GSIL\gsil\config.py", line 53, in <module>
if ',' in tokens:
TypeError: argument of type 'NoneType' is not iterable
大哥大姐们帮帮忙怎么会这样？</module>
