### ISSUE TITLE
关于配置问题

### ISSUE THREAD

**Issue by shenjian216** [FeeiCN/GSIL#46]
你好，我想请问下我配置好了config.gsil.example文件，配置信息如下：
[mail]
host : smtp.exmail.qq.com
port : 25
mails : 10***13@qq.com
from : GSIL
password : 上述qq邮箱的密码
to : feei@feei.cn
cc : feei@feei.cn

[github]
clone: false
tokens : 我自己账号github上token

还是出现了如下错误：
E:\python\python.exe E:/git/Git/gsil/gsil.py
github tokens
GSIL/config.gsil file configure failed.
Error: No section: 'github'
Traceback (most recent call last):
  File "E:\git\Git\gsil\gsil\config.py", line 42, in get
    value = config.get(level1, level2)
  File "E:\python\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "E:\python\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'github'
2018-12-24 16:21:00,855 [GSIL] [CRITICAL] github -> tokens sections error Traceback (most recent call last):
  File "E:\git\Git\gsil\gsil\config.py", line 53, in <module>
    if ',' in tokens:
TypeError: argument of type 'NoneType' is not iterable
我想请问下是哪里出了问题，谢谢了。

**Comment by FeeiCN** [comment]
tokens配置有问题，注意分号要半角
