### ISSUE TITLE
跑着跑着出现了错误,另外请问一个rules的配置问题

### ISSUE THREAD

**Issue by steward007** [FeeiCN/GSIL#48]
错误代码如下:`
```Traceback (most recent call last):
  File "/root/GSIL/gsil/gsil/__init__.py", line 37, in search
    return Engine(token=token).search(rule)
  File "/root/GSIL/gsil/gsil/engine.py", line 220, in search
    Process(self.result, self.rule_object).process()
  File "/root/GSIL/gsil/gsil/process.py", line 36, in process
    ret_mail = self._send_mail(maybe_mistake)
  File "/root/GSIL/gsil/gsil/process.py", line 67, in _send_mail
    self._save_file(v['hash'], v['code'])
  File "/root/GSIL/gsil/gsil/process.py", line 79, in _save_file
    with open(os.path.join(Config().data_path, sha), 'w+', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function```

想问一下多扫描的时候,配置文件是应该这样设置吗:

```{
    "csdn": {
        "csdn.com": {
            "\"password\"": {
                "mode": "normal-match",
                "ext": "php,java,python,go,js,properties"
            }
        }
    }
},
{
    "test": {
        "baidu.com": {
            "\"password\"": {
                "mode": "normal-match",
                "ext": "php,java,python,go,js,properties"
            }
        }
    }
}```

**Comment by FeeiCN** [comment]
使用Python3
