### ISSUE TITLE
请教这报错是邮箱的问题吗？

### ISSUE THREAD

**Issue by 211guns** [FeeiCN/GSIL#65]
2019-11-12 07:53:28,997 [GSIL] [INFO] Process count: 36
Traceback (most recent call last):
  File "/root/GSIL-master/gsil/__init__.py", line 37, in search
    return Engine(token=token).search(rule)
  File "/root/GSIL-master/gsil/engine.py", line 217, in search
    Process(self.result, self.rule_object).process()
  File "/root/GSIL-master/gsil/process.py", line 36, in process
    ret_mail = self._send_mail(maybe_mistake)
  File "/root/GSIL-master/gsil/process.py", line 69, in _send_mail
    return Notification(subject, to, cc).notification(html)
  File "/root/GSIL-master/gsil/notification.py", line 67, in notification
    s = smtplib.SMTP(host, port)
  File "/usr/local/python3/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/python3/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/python3/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/python3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/python3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

邮箱配置的smtp.qq.com
端口25也试了，465也不行
password也是填的授权码

**Comment by FeeiCN** [comment]
邮箱问题，检查网络配置
