### ISSUE TITLE
请教一下，socket.timeout: timed out是什么原因，主机curl github是正常的

### ISSUE THREAD

**Issue by manchesxia** [FeeiCN/GSIL#76]
Traceback (most recent call last):
  File "/root/QQ/GSIL1/GSIL/gsil/__init__.py", line 37, in search
    return Engine(token=token).search(rule)
  File "/root/QQ/GSIL1/GSIL/gsil/engine.py", line 162, in search
    rate_limiting = self.g.rate_limiting
  File "/usr/local/lib/python3.6/site-packages/github/MainClass.py", line 123, in rate_limiting
    self.get_rate_limit()
  File "/usr/local/lib/python3.6/site-packages/github/MainClass.py", line 145, in get_rate_limit
    '/rate_limit'
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 277, in __requestRaw
    requestHeaders
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

**Comment by manchesxia** [comment]
能收邮件，但是报错。。
![image](https://user-images.githubusercontent.com/17880581/151011490-f0ec93f7-2ea0-47cb-8710-ee6754c00ae9.png)
