### ISSUE TITLE
➜  GSIL git:(master) ✗ python gsil.py test  按照官方提示执行这步报错了，可以告知一下原因吗？

### ISSUE THREAD

**Issue by Josie-ljw** [FeeiCN/GSIL#81]
➜  GSIL git:(master) ✗ python gsil.py test
Traceback (most recent call last):
  File "gsil.py", line 20, in <module>
    from gsil import gsil
  File "/Work/GSIL/gsil/__init__.py", line 57
    rule = f'[{r_rule.types}][{r_rule.corp}][{r_rule.keyword}]'
                                                              ^
SyntaxError: invalid syntax

rules.gsil.yaml文件跟示例一模一样

**Comment by Josie-ljw** [comment]
python版本不对
