### ISSUE TITLE
直接用的rules.gsil.example，不能解析。

### ISSUE THREAD

**Issue by fun1355** [FeeiCN/GSIL#9]
(p3.6) ➜  gsil git:(master) ✗ python gsil.py test
github tokens
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'github'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/mac/Develop/gsil/gsil/config.py", line 42, in get
    value = config.get(level1, level2)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'github'
GSIL/config.gsil file configure failed.
Error: No section: 'github'

(p3.6) ➜  gsil git:(master) ✗ cat gsil/rules.gsil 
{
    "test": {
        "mogujie.com": {
            "\"mogujie.org\"": {}
        }
    }
}

(p3.6) ➜  gsil git:(master) ✗ cat gsil/config.gsil 
[mail]
host : smtp.163.com
port : 465
mails : xxx@163.com
from : GSIL
password : xxx
to : xxx@163.com

[github]
clone: false
tokens : xxxx1253

**Comment by FeeiCN** [comment]
提示的错误是`config.gsil`中没有`[github]`节点，看你cat的结果也有这个节点，无法复现这个问题。
尝试删除所有配置文件，再配置下试试？

**Comment by fun1355** [comment]
我删除了两个配置，直接运行，也是报一样的错。可能是根本没读配置。
我傻了，我将配置cp 到 gsil目录了，应该放根目录，就可以了。close吧。
